const express = require('express');
const OngController = require('./controllers/OngsController');
const incidentController = require('./controllers/incidentController');
const ProfileController = require('./controllers/ProfileController');
const SessionController = require('./controllers/SessionController');
const routes = express.Router();
routes.post('/sessions',SessionController.index);
routes.get('/ongs',OngController.index);
routes.get('/profile',ProfileController.index);
routes.post('/ongs',OngController.create);
routes.get('/incidents',incidentController.index);
routes.post('/incidents',incidentController.create);
routes.delete('/incidents/:id',incidentController.delete);
module.exports= routes;